# unpacking-in-except (E1603)
*Implicit unpacking of exceptions is not supported in Python 3* Python3
will not allow implicit unpacking of exceptions in except clauses. See
<http://www.python.org/dev/peps/pep-3110/>
